version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:6969"
      WATCHPACK_POLLING: true
    # env_file:
    #   - ./.env

    stdin_open: true
    tty: true

    # restart: always
    # networks:
      # - react-express
    # depends_on:
    #   - backend


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    environment:
      ATLAS_URI: mongodb://root:example@mongo:27017/
      
      NODE_ENV: production
      DB_HOST: db
      DB_NAME: counter
      DB_USER: postgres
      DB_PASSWORD: password
      PASSPHRASE: secret
    depends_on:
      - mongo-express

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/