FROM node:20-alpine3.17


WORKDIR /usr/src/app
# WORKDIR /backend

RUN chgrp -R 0 /usr/src/app && \
    chmod -R g=u /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
# ENV PATH /backend/node_modules/.bin:$PATH

COPY package*.json ./
# RUN npm install --unsafe-perm -g
RUN npm cache clean --force
RUN npm install

COPY . .

# RUN chown -R 1000:0 /backend && chmod -R ug+rwx /backend
# USER 1000
EXPOSE 6969

CMD ["node", "./src/server.js"]
